// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Car_gui

#include "ui.h"

// void Car1Mode(lv_event_t * e)
// {
// 	// Your code here
// }

// void Car1OnOff(lv_event_t * e)
// {
// 	// Your code here
// }

// void Car1Speed(lv_event_t * e)
// {
// 	// Your code here
// }

// void Car1Io1Func(lv_event_t * e)
// {
// 	// Your code here
// }

// void Car1Io2Func(lv_event_t * e)
// {
// 	// Your code here
// }

// void Car1Io3Func(lv_event_t * e)
// {
// 	// Your code here
// }

// void Car1Io4Func(lv_event_t * e)
// {
// 	// Your code here
// }

// void Car1Io6Func(lv_event_t * e)
// {
// 	// Your code here
// }

// void Car1Io5Func(lv_event_t * e)
// {
// 	// Your code here
// }

// void OnOffAllCar(lv_event_t * e)
// {
// 	// Your code here
// }

// void Car2Mode(lv_event_t * e)
// {
// 	// Your code here
// }

// void Car2OnOff(lv_event_t * e)
// {
// 	// Your code here
// }

// void Car2Speed(lv_event_t * e)
// {
// 	// Your code here
// }

// void Car2Io1Func(lv_event_t * e)
// {
// 	// Your code here
// }

// void Car2Io2Func(lv_event_t * e)
// {
// 	// Your code here
// }

// void Car2Io3Func(lv_event_t * e)
// {
// 	// Your code here
// }

// void Car2Io4Func(lv_event_t * e)
// {
// 	// Your code here
// }

// void Car2Io6Func(lv_event_t * e)
// {
// 	// Your code here
// }

// void Car2Io5Func(lv_event_t * e)
// {
// 	// Your code here
// }

void Car3Mode(lv_event_t * e)
{
	// Your code here
}

void Car3OnOff(lv_event_t * e)
{
	// Your code here
}

void Car3Speed(lv_event_t * e)
{
	// Your code here
}

void Car3Io1Func(lv_event_t * e)
{
	// Your code here
}

void Car3Io2Func(lv_event_t * e)
{
	// Your code here
}

void Car3Io3Func(lv_event_t * e)
{
	// Your code here
}

void Car4Io4Func(lv_event_t * e)
{
	// Your code here
}

void Car5Io6Func(lv_event_t * e)
{
	// Your code here
}

void Car5Io5Func(lv_event_t * e)
{
	// Your code here
}

void Car4Mode(lv_event_t * e)
{
	// Your code here
}

void Car4OnOff(lv_event_t * e)
{
	// Your code here
}

void Car4Speed(lv_event_t * e)
{
	// Your code here
}

void Car5Io1Func(lv_event_t * e)
{
	// Your code here
}

void Car5Io2Func(lv_event_t * e)
{
	// Your code here
}

void Car5Io3Func(lv_event_t * e)
{
	// Your code here
}

void Car5Io4Func(lv_event_t * e)
{
	// Your code here
}

void Car3Io4Func(lv_event_t * e)
{
	// Your code here
}

void Car3Io6Func(lv_event_t * e)
{
	// Your code here
}

void Car3Io5Func(lv_event_t * e)
{
	// Your code here
}

void Car4Io1Func(lv_event_t * e)
{
	// Your code here
}

void Car4Io2Func(lv_event_t * e)
{
	// Your code here
}

void Car4Io3Func(lv_event_t * e)
{
	// Your code here
}

void Car4Io6Func(lv_event_t * e)
{
	// Your code here
}

void Car4Io5Func(lv_event_t * e)
{
	// Your code here
}

void Car5Mode(lv_event_t * e)
{
	// Your code here
}

void Car5OnOff(lv_event_t * e)
{
	// Your code here
}

void Car5Speed(lv_event_t * e)
{
	// Your code here
}

// void SpeedAll(lv_event_t * e)
// {
// 	// Your code here
// }
