// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Car_gui

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_MainPanel = NULL;
lv_obj_t * ui_CarStatus = NULL;
lv_obj_t * ui_Car1 = NULL;
lv_obj_t * ui_Car1panel = NULL;
lv_obj_t * ui_Modepanel = NULL;
lv_obj_t * ui_ModeCarLabel = NULL;
lv_obj_t * ui_MotorMode = NULL;
lv_obj_t * ui_OnOffpanel = NULL;
lv_obj_t * ui_OnOffCarLabel = NULL;
lv_obj_t * ui_OnOffAllCarbtn3 = NULL;
lv_obj_t * ui_Speedpanel = NULL;
lv_obj_t * ui_OnOffCarLabel3 = NULL;
lv_obj_t * ui_Dropdown2 = NULL;
lv_obj_t * ui_OnOffpanel2 = NULL;
lv_obj_t * ui_OnOffCarLabel2 = NULL;
lv_obj_t * ui_OnOffAllCarbtn2 = NULL;
lv_obj_t * ui_OnOffpanel3 = NULL;
lv_obj_t * ui_OnOffCarLabel4 = NULL;
lv_obj_t * ui_OnOffAllCarbtn4 = NULL;
lv_obj_t * ui_OnOffpanel1 = NULL;
lv_obj_t * ui_OnOffCarLabel1 = NULL;
lv_obj_t * ui_OnOffAllCarbtn1 = NULL;
lv_obj_t * ui_OnOffpanel4 = NULL;
lv_obj_t * ui_OnOffCarLabel5 = NULL;
lv_obj_t * ui_OnOffAllCarbtn5 = NULL;
lv_obj_t * ui_OnOffpanel5 = NULL;
lv_obj_t * ui_OnOffCarLabel6 = NULL;
lv_obj_t * ui_OnOffAllCarbtn6 = NULL;
lv_obj_t * ui_OnOffpanel6 = NULL;
lv_obj_t * ui_OnOffCarLabel7 = NULL;
lv_obj_t * ui_OnOffAllCarbtn7 = NULL;
lv_obj_t * ui_Batterypanel = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Car1Batlabel = NULL;
lv_obj_t * ui_Car2 = NULL;
lv_obj_t * ui_Car2panel = NULL;
lv_obj_t * ui_Modepanel2 = NULL;
lv_obj_t * ui_ModeCarLabel2 = NULL;
lv_obj_t * ui_MotorMode2 = NULL;
lv_obj_t * ui_OnOffpanel14 = NULL;
lv_obj_t * ui_OnOffCarLabel16 = NULL;
lv_obj_t * ui_OnOffAllCarbtn15 = NULL;
lv_obj_t * ui_Speedpanel2 = NULL;
lv_obj_t * ui_OnOffCarLabel8 = NULL;
lv_obj_t * ui_Dropdown4 = NULL;
lv_obj_t * ui_OnOffpanel7 = NULL;
lv_obj_t * ui_OnOffCarLabel9 = NULL;
lv_obj_t * ui_OnOffAllCarbtn8 = NULL;
lv_obj_t * ui_OnOffpanel8 = NULL;
lv_obj_t * ui_OnOffCarLabel10 = NULL;
lv_obj_t * ui_OnOffAllCarbtn9 = NULL;
lv_obj_t * ui_OnOffpanel9 = NULL;
lv_obj_t * ui_OnOffCarLabel11 = NULL;
lv_obj_t * ui_OnOffAllCarbtn10 = NULL;
lv_obj_t * ui_OnOffpanel10 = NULL;
lv_obj_t * ui_OnOffCarLabel12 = NULL;
lv_obj_t * ui_OnOffAllCarbtn11 = NULL;
lv_obj_t * ui_OnOffpanel11 = NULL;
lv_obj_t * ui_OnOffCarLabel13 = NULL;
lv_obj_t * ui_OnOffAllCarbtn12 = NULL;
lv_obj_t * ui_OnOffpanel12 = NULL;
lv_obj_t * ui_OnOffCarLabel14 = NULL;
lv_obj_t * ui_OnOffAllCarbtn13 = NULL;
lv_obj_t * ui_Batterypanel2 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Car2Batlabel = NULL;
lv_obj_t * ui_Car3 = NULL;
lv_obj_t * ui_Car3panel = NULL;
lv_obj_t * ui_Modepanel3 = NULL;
lv_obj_t * ui_ModeCarLabel3 = NULL;
lv_obj_t * ui_MotorMode3 = NULL;
lv_obj_t * ui_OnOffpanel15 = NULL;
lv_obj_t * ui_OnOffCarLabel17 = NULL;
lv_obj_t * ui_OnOffAllCarbtn16 = NULL;
lv_obj_t * ui_Speedpanel3 = NULL;
lv_obj_t * ui_OnOffCarLabel18 = NULL;
lv_obj_t * ui_Dropdown5 = NULL;
lv_obj_t * ui_OnOffpanel16 = NULL;
lv_obj_t * ui_OnOffCarLabel19 = NULL;
lv_obj_t * ui_OnOffAllCarbtn17 = NULL;
lv_obj_t * ui_OnOffpanel17 = NULL;
lv_obj_t * ui_OnOffCarLabel20 = NULL;
lv_obj_t * ui_OnOffAllCarbtn18 = NULL;
lv_obj_t * ui_OnOffpanel18 = NULL;
lv_obj_t * ui_OnOffCarLabel21 = NULL;
lv_obj_t * ui_OnOffAllCarbtn19 = NULL;
lv_obj_t * ui_OnOffpanel19 = NULL;
lv_obj_t * ui_OnOffCarLabel22 = NULL;
lv_obj_t * ui_OnOffAllCarbtn20 = NULL;
lv_obj_t * ui_OnOffpanel20 = NULL;
lv_obj_t * ui_OnOffCarLabel23 = NULL;
lv_obj_t * ui_OnOffAllCarbtn21 = NULL;
lv_obj_t * ui_OnOffpanel21 = NULL;
lv_obj_t * ui_OnOffCarLabel24 = NULL;
lv_obj_t * ui_OnOffAllCarbtn22 = NULL;
lv_obj_t * ui_Batterypanel3 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Car3Batlabel = NULL;
lv_obj_t * ui_Car4 = NULL;
lv_obj_t * ui_Car4panel = NULL;
lv_obj_t * ui_Modepanel4 = NULL;
lv_obj_t * ui_ModeCarLabel4 = NULL;
lv_obj_t * ui_MotorMode4 = NULL;
lv_obj_t * ui_OnOffpanel22 = NULL;
lv_obj_t * ui_OnOffCarLabel25 = NULL;
lv_obj_t * ui_OnOffAllCarbtn23 = NULL;
lv_obj_t * ui_Speedpanel4 = NULL;
lv_obj_t * ui_OnOffCarLabel26 = NULL;
lv_obj_t * ui_Dropdown6 = NULL;
lv_obj_t * ui_OnOffpanel23 = NULL;
lv_obj_t * ui_OnOffCarLabel27 = NULL;
lv_obj_t * ui_OnOffAllCarbtn24 = NULL;
lv_obj_t * ui_OnOffpanel24 = NULL;
lv_obj_t * ui_OnOffCarLabel28 = NULL;
lv_obj_t * ui_OnOffAllCarbtn25 = NULL;
lv_obj_t * ui_OnOffpanel25 = NULL;
lv_obj_t * ui_OnOffCarLabel29 = NULL;
lv_obj_t * ui_OnOffAllCarbtn26 = NULL;
lv_obj_t * ui_OnOffpanel26 = NULL;
lv_obj_t * ui_OnOffCarLabel30 = NULL;
lv_obj_t * ui_OnOffAllCarbtn27 = NULL;
lv_obj_t * ui_OnOffpanel27 = NULL;
lv_obj_t * ui_OnOffCarLabel31 = NULL;
lv_obj_t * ui_OnOffAllCarbtn28 = NULL;
lv_obj_t * ui_OnOffpanel28 = NULL;
lv_obj_t * ui_OnOffCarLabel32 = NULL;
lv_obj_t * ui_OnOffAllCarbtn29 = NULL;
lv_obj_t * ui_Batterypanel4 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Car4Batlabel = NULL;
lv_obj_t * ui_Car5 = NULL;
lv_obj_t * ui_Car5panel = NULL;
lv_obj_t * ui_Modepanel5 = NULL;
lv_obj_t * ui_ModeCarLabel5 = NULL;
lv_obj_t * ui_MotorMode5 = NULL;
lv_obj_t * ui_OnOffpanel29 = NULL;
lv_obj_t * ui_OnOffCarLabel33 = NULL;
lv_obj_t * ui_OnOffAllCarbtn30 = NULL;
lv_obj_t * ui_Speedpanel6 = NULL;
lv_obj_t * ui_OnOffCarLabel35 = NULL;
lv_obj_t * ui_Dropdown7 = NULL;
lv_obj_t * ui_OnOffpanel30 = NULL;
lv_obj_t * ui_OnOffCarLabel36 = NULL;
lv_obj_t * ui_OnOffAllCarbtn31 = NULL;
lv_obj_t * ui_OnOffpanel31 = NULL;
lv_obj_t * ui_OnOffCarLabel37 = NULL;
lv_obj_t * ui_OnOffAllCarbtn32 = NULL;
lv_obj_t * ui_OnOffpanel32 = NULL;
lv_obj_t * ui_OnOffCarLabel38 = NULL;
lv_obj_t * ui_OnOffAllCarbtn33 = NULL;
lv_obj_t * ui_OnOffpanel33 = NULL;
lv_obj_t * ui_OnOffCarLabel39 = NULL;
lv_obj_t * ui_OnOffAllCarbtn34 = NULL;
lv_obj_t * ui_OnOffpanel34 = NULL;
lv_obj_t * ui_OnOffCarLabel40 = NULL;
lv_obj_t * ui_OnOffAllCarbtn35 = NULL;
lv_obj_t * ui_OnOffpanel35 = NULL;
lv_obj_t * ui_OnOffCarLabel41 = NULL;
lv_obj_t * ui_OnOffAllCarbtn36 = NULL;
lv_obj_t * ui_Batterypanel5 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Car5Batlabel = NULL;
lv_obj_t * ui_StatusArea = NULL;
lv_obj_t * ui_SpeedAllpanel = NULL;
lv_obj_t * ui_SpeedAllCarLabel = NULL;
lv_obj_t * ui_SpeedAllCardropdown = NULL;
lv_obj_t * ui_OnOffAllCarbtn = NULL;
lv_obj_t * ui_OnOffAllCarlabel = NULL;
// event funtions
void ui_event_MotorMode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car1Mode(e);
    }
}

void ui_event_OnOffAllCarbtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car1OnOff(e);
    }
}

void ui_event_Dropdown2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car1Speed(e);
    }
}

void ui_event_OnOffAllCarbtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car1Io1Func(e);
    }
}

void ui_event_OnOffAllCarbtn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car1Io2Func(e);
    }
}

void ui_event_OnOffAllCarbtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car1Io3Func(e);
    }
}

void ui_event_OnOffAllCarbtn5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car1Io4Func(e);
    }
}

void ui_event_OnOffAllCarbtn6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car1Io6Func(e);
    }
}

void ui_event_OnOffAllCarbtn7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car1Io5Func(e);
    }
}

void ui_event_MotorMode2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car2Mode(e);
    }
}

void ui_event_OnOffAllCarbtn15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car2OnOff(e);
    }
}

void ui_event_Dropdown4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car2Speed(e);
    }
}

void ui_event_OnOffAllCarbtn8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car2Io1Func(e);
    }
}

void ui_event_OnOffAllCarbtn9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car2Io2Func(e);
    }
}

void ui_event_OnOffAllCarbtn10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car2Io3Func(e);
    }
}

void ui_event_OnOffAllCarbtn11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car2Io4Func(e);
    }
}

void ui_event_OnOffAllCarbtn12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car2Io6Func(e);
    }
}

void ui_event_OnOffAllCarbtn13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car2Io5Func(e);
    }
}

void ui_event_MotorMode3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car3Mode(e);
    }
}

void ui_event_OnOffAllCarbtn16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car3OnOff(e);
    }
}

void ui_event_Dropdown5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car3Speed(e);
    }
}

void ui_event_OnOffAllCarbtn17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car3Io1Func(e);
    }
}

void ui_event_OnOffAllCarbtn18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car3Io2Func(e);
    }
}

void ui_event_OnOffAllCarbtn19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car3Io3Func(e);
    }
}

void ui_event_OnOffAllCarbtn20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car3Io4Func(e);
    }
}

void ui_event_OnOffAllCarbtn21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car3Io6Func(e);
    }
}

void ui_event_OnOffAllCarbtn22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car3Io5Func(e);
    }
}

void ui_event_MotorMode4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car4Mode(e);
    }
}

void ui_event_OnOffAllCarbtn23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car4OnOff(e);
    }
}

void ui_event_Dropdown6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car4Speed(e);
    }
}

void ui_event_OnOffAllCarbtn24(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car4Io1Func(e);
    }
}

void ui_event_OnOffAllCarbtn25(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car4Io2Func(e);
    }
}

void ui_event_OnOffAllCarbtn26(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car4Io3Func(e);
    }
}

void ui_event_OnOffAllCarbtn27(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car4Io4Func(e);
    }
}

void ui_event_OnOffAllCarbtn28(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car4Io6Func(e);
    }
}

void ui_event_OnOffAllCarbtn29(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car4Io5Func(e);
    }
}

void ui_event_MotorMode5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car5Mode(e);
    }
}

void ui_event_OnOffAllCarbtn30(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car5OnOff(e);
    }
}

void ui_event_Dropdown7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car5Speed(e);
    }
}

void ui_event_OnOffAllCarbtn31(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car5Io1Func(e);
    }
}

void ui_event_OnOffAllCarbtn32(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car5Io2Func(e);
    }
}

void ui_event_OnOffAllCarbtn33(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car5Io3Func(e);
    }
}

void ui_event_OnOffAllCarbtn34(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car5Io4Func(e);
    }
}

void ui_event_OnOffAllCarbtn35(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car5Io6Func(e);
    }
}

void ui_event_OnOffAllCarbtn36(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Car5Io5Func(e);
    }
}

void ui_event_SpeedAllCardropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SpeedAll(e);
    }
}

void ui_event_OnOffAllCarbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnOffAllCar(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_MainPanel, 786);
    lv_obj_set_height(ui_MainPanel, 464);
    lv_obj_set_x(ui_MainPanel, 0);
    lv_obj_set_y(ui_MainPanel, 1);
    lv_obj_set_align(ui_MainPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CarStatus = lv_tabview_create(ui_MainPanel, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_CarStatus, 761);
    lv_obj_set_height(ui_CarStatus, 269);
    lv_obj_set_x(ui_CarStatus, -3);
    lv_obj_set_y(ui_CarStatus, 73);
    lv_obj_set_align(ui_CarStatus, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CarStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Car1 = lv_tabview_add_tab(ui_CarStatus, "CAR 1");

    ui_Car1panel = lv_obj_create(ui_Car1);
    lv_obj_set_width(ui_Car1panel, 722);
    lv_obj_set_height(ui_Car1panel, 207);
    lv_obj_set_x(ui_Car1panel, -6);
    lv_obj_set_y(ui_Car1panel, 1);
    lv_obj_set_align(ui_Car1panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Car1panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Modepanel = lv_obj_create(ui_Car1panel);
    lv_obj_set_width(ui_Modepanel, 228);
    lv_obj_set_height(ui_Modepanel, 54);
    lv_obj_set_x(ui_Modepanel, -214);
    lv_obj_set_y(ui_Modepanel, 63);
    lv_obj_set_align(ui_Modepanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Modepanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ModeCarLabel = lv_label_create(ui_Modepanel);
    lv_obj_set_width(ui_ModeCarLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ModeCarLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ModeCarLabel, -61);
    lv_obj_set_y(ui_ModeCarLabel, 0);
    lv_obj_set_align(ui_ModeCarLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ModeCarLabel, "MODE");
    lv_obj_set_style_text_font(ui_ModeCarLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorMode = lv_dropdown_create(ui_Modepanel);
    lv_dropdown_set_options(ui_MotorMode, "Mode 1\nMode 2\n");
    lv_obj_set_width(ui_MotorMode, 107);
    lv_obj_set_height(ui_MotorMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorMode, 49);
    lv_obj_set_y(ui_MotorMode, 0);
    lv_obj_set_align(ui_MotorMode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MotorMode, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_OnOffpanel = lv_obj_create(ui_Car1panel);
    lv_obj_set_width(ui_OnOffpanel, 228);
    lv_obj_set_height(ui_OnOffpanel, 54);
    lv_obj_set_x(ui_OnOffpanel, -214);
    lv_obj_set_y(ui_OnOffpanel, -66);
    lv_obj_set_align(ui_OnOffpanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel = lv_label_create(ui_OnOffpanel);
    lv_obj_set_width(ui_OnOffCarLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel, -56);
    lv_obj_set_y(ui_OnOffCarLabel, 0);
    lv_obj_set_align(ui_OnOffCarLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel, "ON/OFF ");
    lv_obj_set_style_text_font(ui_OnOffCarLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn3 = lv_switch_create(ui_OnOffpanel);
    lv_obj_set_width(ui_OnOffAllCarbtn3, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn3, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn3, 52);
    lv_obj_set_y(ui_OnOffAllCarbtn3, -1);
    lv_obj_set_align(ui_OnOffAllCarbtn3, LV_ALIGN_CENTER);

    ui_Speedpanel = lv_obj_create(ui_Car1panel);
    lv_obj_set_width(ui_Speedpanel, 228);
    lv_obj_set_height(ui_Speedpanel, 54);
    lv_obj_set_x(ui_Speedpanel, -214);
    lv_obj_set_y(ui_Speedpanel, -2);
    lv_obj_set_align(ui_Speedpanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Speedpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel3 = lv_label_create(ui_Speedpanel);
    lv_obj_set_width(ui_OnOffCarLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel3, -61);
    lv_obj_set_y(ui_OnOffCarLabel3, 0);
    lv_obj_set_align(ui_OnOffCarLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel3, "SPEED");
    lv_obj_set_style_text_font(ui_OnOffCarLabel3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown2 = lv_dropdown_create(ui_Speedpanel);
    lv_dropdown_set_options(ui_Dropdown2, "10%\n20%\n30%\n40%\n50%\n60%\n70%\n80%\n90%\n100%");
    lv_obj_set_width(ui_Dropdown2, 107);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, 49);
    lv_obj_set_y(ui_Dropdown2, 0);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_OnOffpanel2 = lv_obj_create(ui_Car1panel);
    lv_obj_set_width(ui_OnOffpanel2, 134);
    lv_obj_set_height(ui_OnOffpanel2, 54);
    lv_obj_set_x(ui_OnOffpanel2, 106);
    lv_obj_set_y(ui_OnOffpanel2, -66);
    lv_obj_set_align(ui_OnOffpanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel2 = lv_label_create(ui_OnOffpanel2);
    lv_obj_set_width(ui_OnOffCarLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel2, -36);
    lv_obj_set_y(ui_OnOffCarLabel2, 0);
    lv_obj_set_align(ui_OnOffCarLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel2, "IO1");
    lv_obj_set_style_text_font(ui_OnOffCarLabel2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn2 = lv_switch_create(ui_OnOffpanel2);
    lv_obj_set_width(ui_OnOffAllCarbtn2, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn2, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn2, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn2, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn2, LV_ALIGN_CENTER);

    ui_OnOffpanel3 = lv_obj_create(ui_Car1panel);
    lv_obj_set_width(ui_OnOffpanel3, 134);
    lv_obj_set_height(ui_OnOffpanel3, 54);
    lv_obj_set_x(ui_OnOffpanel3, 264);
    lv_obj_set_y(ui_OnOffpanel3, -65);
    lv_obj_set_align(ui_OnOffpanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel4 = lv_label_create(ui_OnOffpanel3);
    lv_obj_set_width(ui_OnOffCarLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel4, -36);
    lv_obj_set_y(ui_OnOffCarLabel4, 0);
    lv_obj_set_align(ui_OnOffCarLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel4, "IO2");
    lv_obj_set_style_text_font(ui_OnOffCarLabel4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn4 = lv_switch_create(ui_OnOffpanel3);
    lv_obj_set_width(ui_OnOffAllCarbtn4, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn4, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn4, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn4, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn4, LV_ALIGN_CENTER);

    ui_OnOffpanel1 = lv_obj_create(ui_Car1panel);
    lv_obj_set_width(ui_OnOffpanel1, 134);
    lv_obj_set_height(ui_OnOffpanel1, 54);
    lv_obj_set_x(ui_OnOffpanel1, 106);
    lv_obj_set_y(ui_OnOffpanel1, -2);
    lv_obj_set_align(ui_OnOffpanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel1 = lv_label_create(ui_OnOffpanel1);
    lv_obj_set_width(ui_OnOffCarLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel1, -36);
    lv_obj_set_y(ui_OnOffCarLabel1, 0);
    lv_obj_set_align(ui_OnOffCarLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel1, "IO3");
    lv_obj_set_style_text_font(ui_OnOffCarLabel1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn1 = lv_switch_create(ui_OnOffpanel1);
    lv_obj_set_width(ui_OnOffAllCarbtn1, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn1, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn1, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn1, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn1, LV_ALIGN_CENTER);

    ui_OnOffpanel4 = lv_obj_create(ui_Car1panel);
    lv_obj_set_width(ui_OnOffpanel4, 134);
    lv_obj_set_height(ui_OnOffpanel4, 54);
    lv_obj_set_x(ui_OnOffpanel4, 264);
    lv_obj_set_y(ui_OnOffpanel4, -2);
    lv_obj_set_align(ui_OnOffpanel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel5 = lv_label_create(ui_OnOffpanel4);
    lv_obj_set_width(ui_OnOffCarLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel5, -36);
    lv_obj_set_y(ui_OnOffCarLabel5, 0);
    lv_obj_set_align(ui_OnOffCarLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel5, "IO4");
    lv_obj_set_style_text_font(ui_OnOffCarLabel5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn5 = lv_switch_create(ui_OnOffpanel4);
    lv_obj_set_width(ui_OnOffAllCarbtn5, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn5, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn5, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn5, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn5, LV_ALIGN_CENTER);

    ui_OnOffpanel5 = lv_obj_create(ui_Car1panel);
    lv_obj_set_width(ui_OnOffpanel5, 134);
    lv_obj_set_height(ui_OnOffpanel5, 54);
    lv_obj_set_x(ui_OnOffpanel5, 264);
    lv_obj_set_y(ui_OnOffpanel5, 62);
    lv_obj_set_align(ui_OnOffpanel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel6 = lv_label_create(ui_OnOffpanel5);
    lv_obj_set_width(ui_OnOffCarLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel6, -36);
    lv_obj_set_y(ui_OnOffCarLabel6, 0);
    lv_obj_set_align(ui_OnOffCarLabel6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel6, "IO6");
    lv_obj_set_style_text_font(ui_OnOffCarLabel6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn6 = lv_switch_create(ui_OnOffpanel5);
    lv_obj_set_width(ui_OnOffAllCarbtn6, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn6, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn6, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn6, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn6, LV_ALIGN_CENTER);

    ui_OnOffpanel6 = lv_obj_create(ui_Car1panel);
    lv_obj_set_width(ui_OnOffpanel6, 134);
    lv_obj_set_height(ui_OnOffpanel6, 54);
    lv_obj_set_x(ui_OnOffpanel6, 106);
    lv_obj_set_y(ui_OnOffpanel6, 63);
    lv_obj_set_align(ui_OnOffpanel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel7 = lv_label_create(ui_OnOffpanel6);
    lv_obj_set_width(ui_OnOffCarLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel7, -36);
    lv_obj_set_y(ui_OnOffCarLabel7, 0);
    lv_obj_set_align(ui_OnOffCarLabel7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel7, "IO5");
    lv_obj_set_style_text_font(ui_OnOffCarLabel7, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn7 = lv_switch_create(ui_OnOffpanel6);
    lv_obj_set_width(ui_OnOffAllCarbtn7, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn7, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn7, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn7, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn7, LV_ALIGN_CENTER);

    ui_Batterypanel = lv_obj_create(ui_Car1panel);
    lv_obj_set_width(ui_Batterypanel, 93);
    lv_obj_set_height(ui_Batterypanel, 180);
    lv_obj_set_x(ui_Batterypanel, -28);
    lv_obj_set_y(ui_Batterypanel, 0);
    lv_obj_set_align(ui_Batterypanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Batterypanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Batterypanel);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 1);
    lv_obj_set_y(ui_Label2, -58);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "BAT");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Car1Batlabel = lv_label_create(ui_Batterypanel);
    lv_obj_set_width(ui_Car1Batlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Car1Batlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Car1Batlabel, 0);
    lv_obj_set_y(ui_Car1Batlabel, 6);
    lv_obj_set_align(ui_Car1Batlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Car1Batlabel, "100%");
    lv_obj_set_style_text_color(ui_Car1Batlabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Car1Batlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Car1Batlabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Car1Batlabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Car2 = lv_tabview_add_tab(ui_CarStatus, "CAR 2");

    ui_Car2panel = lv_obj_create(ui_Car2);
    lv_obj_set_width(ui_Car2panel, 722);
    lv_obj_set_height(ui_Car2panel, 207);
    lv_obj_set_x(ui_Car2panel, -6);
    lv_obj_set_y(ui_Car2panel, 1);
    lv_obj_set_align(ui_Car2panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Car2panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Modepanel2 = lv_obj_create(ui_Car2panel);
    lv_obj_set_width(ui_Modepanel2, 228);
    lv_obj_set_height(ui_Modepanel2, 54);
    lv_obj_set_x(ui_Modepanel2, -214);
    lv_obj_set_y(ui_Modepanel2, 63);
    lv_obj_set_align(ui_Modepanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Modepanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ModeCarLabel2 = lv_label_create(ui_Modepanel2);
    lv_obj_set_width(ui_ModeCarLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ModeCarLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ModeCarLabel2, -61);
    lv_obj_set_y(ui_ModeCarLabel2, 0);
    lv_obj_set_align(ui_ModeCarLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ModeCarLabel2, "MODE");
    lv_obj_set_style_text_font(ui_ModeCarLabel2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorMode2 = lv_dropdown_create(ui_Modepanel2);
    lv_dropdown_set_options(ui_MotorMode2, "Mode 1\nMode 2\n");
    lv_obj_set_width(ui_MotorMode2, 107);
    lv_obj_set_height(ui_MotorMode2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorMode2, 49);
    lv_obj_set_y(ui_MotorMode2, 0);
    lv_obj_set_align(ui_MotorMode2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MotorMode2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_OnOffpanel14 = lv_obj_create(ui_Car2panel);
    lv_obj_set_width(ui_OnOffpanel14, 228);
    lv_obj_set_height(ui_OnOffpanel14, 54);
    lv_obj_set_x(ui_OnOffpanel14, -214);
    lv_obj_set_y(ui_OnOffpanel14, -66);
    lv_obj_set_align(ui_OnOffpanel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel16 = lv_label_create(ui_OnOffpanel14);
    lv_obj_set_width(ui_OnOffCarLabel16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel16, -56);
    lv_obj_set_y(ui_OnOffCarLabel16, 0);
    lv_obj_set_align(ui_OnOffCarLabel16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel16, "ON/OFF ");
    lv_obj_set_style_text_font(ui_OnOffCarLabel16, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn15 = lv_switch_create(ui_OnOffpanel14);
    lv_obj_set_width(ui_OnOffAllCarbtn15, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn15, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn15, 52);
    lv_obj_set_y(ui_OnOffAllCarbtn15, -1);
    lv_obj_set_align(ui_OnOffAllCarbtn15, LV_ALIGN_CENTER);

    ui_Speedpanel2 = lv_obj_create(ui_Car2panel);
    lv_obj_set_width(ui_Speedpanel2, 228);
    lv_obj_set_height(ui_Speedpanel2, 54);
    lv_obj_set_x(ui_Speedpanel2, -214);
    lv_obj_set_y(ui_Speedpanel2, -2);
    lv_obj_set_align(ui_Speedpanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Speedpanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel8 = lv_label_create(ui_Speedpanel2);
    lv_obj_set_width(ui_OnOffCarLabel8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel8, -61);
    lv_obj_set_y(ui_OnOffCarLabel8, 0);
    lv_obj_set_align(ui_OnOffCarLabel8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel8, "SPEED");
    lv_obj_set_style_text_font(ui_OnOffCarLabel8, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown4 = lv_dropdown_create(ui_Speedpanel2);
    lv_dropdown_set_options(ui_Dropdown4, "10%\n20%\n30%\n40%\n50%\n60%\n70%\n80%\n90%\n100%");
    lv_obj_set_width(ui_Dropdown4, 107);
    lv_obj_set_height(ui_Dropdown4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown4, 49);
    lv_obj_set_y(ui_Dropdown4, 0);
    lv_obj_set_align(ui_Dropdown4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_OnOffpanel7 = lv_obj_create(ui_Car2panel);
    lv_obj_set_width(ui_OnOffpanel7, 134);
    lv_obj_set_height(ui_OnOffpanel7, 54);
    lv_obj_set_x(ui_OnOffpanel7, 106);
    lv_obj_set_y(ui_OnOffpanel7, -66);
    lv_obj_set_align(ui_OnOffpanel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel9 = lv_label_create(ui_OnOffpanel7);
    lv_obj_set_width(ui_OnOffCarLabel9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel9, -36);
    lv_obj_set_y(ui_OnOffCarLabel9, 0);
    lv_obj_set_align(ui_OnOffCarLabel9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel9, "IO1");
    lv_obj_set_style_text_font(ui_OnOffCarLabel9, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn8 = lv_switch_create(ui_OnOffpanel7);
    lv_obj_set_width(ui_OnOffAllCarbtn8, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn8, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn8, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn8, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn8, LV_ALIGN_CENTER);

    ui_OnOffpanel8 = lv_obj_create(ui_Car2panel);
    lv_obj_set_width(ui_OnOffpanel8, 134);
    lv_obj_set_height(ui_OnOffpanel8, 54);
    lv_obj_set_x(ui_OnOffpanel8, 264);
    lv_obj_set_y(ui_OnOffpanel8, -65);
    lv_obj_set_align(ui_OnOffpanel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel10 = lv_label_create(ui_OnOffpanel8);
    lv_obj_set_width(ui_OnOffCarLabel10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel10, -36);
    lv_obj_set_y(ui_OnOffCarLabel10, 0);
    lv_obj_set_align(ui_OnOffCarLabel10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel10, "IO2");
    lv_obj_set_style_text_font(ui_OnOffCarLabel10, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn9 = lv_switch_create(ui_OnOffpanel8);
    lv_obj_set_width(ui_OnOffAllCarbtn9, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn9, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn9, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn9, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn9, LV_ALIGN_CENTER);

    ui_OnOffpanel9 = lv_obj_create(ui_Car2panel);
    lv_obj_set_width(ui_OnOffpanel9, 134);
    lv_obj_set_height(ui_OnOffpanel9, 54);
    lv_obj_set_x(ui_OnOffpanel9, 106);
    lv_obj_set_y(ui_OnOffpanel9, -2);
    lv_obj_set_align(ui_OnOffpanel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel11 = lv_label_create(ui_OnOffpanel9);
    lv_obj_set_width(ui_OnOffCarLabel11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel11, -36);
    lv_obj_set_y(ui_OnOffCarLabel11, 0);
    lv_obj_set_align(ui_OnOffCarLabel11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel11, "IO3");
    lv_obj_set_style_text_font(ui_OnOffCarLabel11, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn10 = lv_switch_create(ui_OnOffpanel9);
    lv_obj_set_width(ui_OnOffAllCarbtn10, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn10, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn10, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn10, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn10, LV_ALIGN_CENTER);

    ui_OnOffpanel10 = lv_obj_create(ui_Car2panel);
    lv_obj_set_width(ui_OnOffpanel10, 134);
    lv_obj_set_height(ui_OnOffpanel10, 54);
    lv_obj_set_x(ui_OnOffpanel10, 264);
    lv_obj_set_y(ui_OnOffpanel10, -2);
    lv_obj_set_align(ui_OnOffpanel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel12 = lv_label_create(ui_OnOffpanel10);
    lv_obj_set_width(ui_OnOffCarLabel12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel12, -36);
    lv_obj_set_y(ui_OnOffCarLabel12, 0);
    lv_obj_set_align(ui_OnOffCarLabel12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel12, "IO4");
    lv_obj_set_style_text_font(ui_OnOffCarLabel12, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn11 = lv_switch_create(ui_OnOffpanel10);
    lv_obj_set_width(ui_OnOffAllCarbtn11, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn11, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn11, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn11, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn11, LV_ALIGN_CENTER);

    ui_OnOffpanel11 = lv_obj_create(ui_Car2panel);
    lv_obj_set_width(ui_OnOffpanel11, 134);
    lv_obj_set_height(ui_OnOffpanel11, 54);
    lv_obj_set_x(ui_OnOffpanel11, 264);
    lv_obj_set_y(ui_OnOffpanel11, 62);
    lv_obj_set_align(ui_OnOffpanel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel13 = lv_label_create(ui_OnOffpanel11);
    lv_obj_set_width(ui_OnOffCarLabel13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel13, -36);
    lv_obj_set_y(ui_OnOffCarLabel13, 0);
    lv_obj_set_align(ui_OnOffCarLabel13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel13, "IO6");
    lv_obj_set_style_text_font(ui_OnOffCarLabel13, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn12 = lv_switch_create(ui_OnOffpanel11);
    lv_obj_set_width(ui_OnOffAllCarbtn12, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn12, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn12, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn12, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn12, LV_ALIGN_CENTER);

    ui_OnOffpanel12 = lv_obj_create(ui_Car2panel);
    lv_obj_set_width(ui_OnOffpanel12, 134);
    lv_obj_set_height(ui_OnOffpanel12, 54);
    lv_obj_set_x(ui_OnOffpanel12, 106);
    lv_obj_set_y(ui_OnOffpanel12, 63);
    lv_obj_set_align(ui_OnOffpanel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel14 = lv_label_create(ui_OnOffpanel12);
    lv_obj_set_width(ui_OnOffCarLabel14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel14, -36);
    lv_obj_set_y(ui_OnOffCarLabel14, 0);
    lv_obj_set_align(ui_OnOffCarLabel14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel14, "IO5");
    lv_obj_set_style_text_font(ui_OnOffCarLabel14, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn13 = lv_switch_create(ui_OnOffpanel12);
    lv_obj_set_width(ui_OnOffAllCarbtn13, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn13, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn13, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn13, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn13, LV_ALIGN_CENTER);

    ui_Batterypanel2 = lv_obj_create(ui_Car2panel);
    lv_obj_set_width(ui_Batterypanel2, 93);
    lv_obj_set_height(ui_Batterypanel2, 180);
    lv_obj_set_x(ui_Batterypanel2, -28);
    lv_obj_set_y(ui_Batterypanel2, 0);
    lv_obj_set_align(ui_Batterypanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Batterypanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Batterypanel2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 1);
    lv_obj_set_y(ui_Label5, -58);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "BAT");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Car2Batlabel = lv_label_create(ui_Batterypanel2);
    lv_obj_set_width(ui_Car2Batlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Car2Batlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Car2Batlabel, 0);
    lv_obj_set_y(ui_Car2Batlabel, 6);
    lv_obj_set_align(ui_Car2Batlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Car2Batlabel, "100%");
    lv_obj_set_style_text_color(ui_Car2Batlabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Car2Batlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Car2Batlabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Car2Batlabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Car3 = lv_tabview_add_tab(ui_CarStatus, "CAR 3");

    ui_Car3panel = lv_obj_create(ui_Car3);
    lv_obj_set_width(ui_Car3panel, 722);
    lv_obj_set_height(ui_Car3panel, 207);
    lv_obj_set_x(ui_Car3panel, -6);
    lv_obj_set_y(ui_Car3panel, 1);
    lv_obj_set_align(ui_Car3panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Car3panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Modepanel3 = lv_obj_create(ui_Car3panel);
    lv_obj_set_width(ui_Modepanel3, 228);
    lv_obj_set_height(ui_Modepanel3, 54);
    lv_obj_set_x(ui_Modepanel3, -214);
    lv_obj_set_y(ui_Modepanel3, 63);
    lv_obj_set_align(ui_Modepanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Modepanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ModeCarLabel3 = lv_label_create(ui_Modepanel3);
    lv_obj_set_width(ui_ModeCarLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ModeCarLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ModeCarLabel3, -61);
    lv_obj_set_y(ui_ModeCarLabel3, 0);
    lv_obj_set_align(ui_ModeCarLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ModeCarLabel3, "MODE");
    lv_obj_set_style_text_font(ui_ModeCarLabel3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorMode3 = lv_dropdown_create(ui_Modepanel3);
    lv_dropdown_set_options(ui_MotorMode3, "Mode 1\nMode 2\n");
    lv_obj_set_width(ui_MotorMode3, 107);
    lv_obj_set_height(ui_MotorMode3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorMode3, 49);
    lv_obj_set_y(ui_MotorMode3, 0);
    lv_obj_set_align(ui_MotorMode3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MotorMode3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_OnOffpanel15 = lv_obj_create(ui_Car3panel);
    lv_obj_set_width(ui_OnOffpanel15, 228);
    lv_obj_set_height(ui_OnOffpanel15, 54);
    lv_obj_set_x(ui_OnOffpanel15, -214);
    lv_obj_set_y(ui_OnOffpanel15, -66);
    lv_obj_set_align(ui_OnOffpanel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel17 = lv_label_create(ui_OnOffpanel15);
    lv_obj_set_width(ui_OnOffCarLabel17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel17, -56);
    lv_obj_set_y(ui_OnOffCarLabel17, 0);
    lv_obj_set_align(ui_OnOffCarLabel17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel17, "ON/OFF ");
    lv_obj_set_style_text_font(ui_OnOffCarLabel17, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn16 = lv_switch_create(ui_OnOffpanel15);
    lv_obj_set_width(ui_OnOffAllCarbtn16, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn16, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn16, 52);
    lv_obj_set_y(ui_OnOffAllCarbtn16, -1);
    lv_obj_set_align(ui_OnOffAllCarbtn16, LV_ALIGN_CENTER);

    ui_Speedpanel3 = lv_obj_create(ui_Car3panel);
    lv_obj_set_width(ui_Speedpanel3, 228);
    lv_obj_set_height(ui_Speedpanel3, 54);
    lv_obj_set_x(ui_Speedpanel3, -214);
    lv_obj_set_y(ui_Speedpanel3, -2);
    lv_obj_set_align(ui_Speedpanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Speedpanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel18 = lv_label_create(ui_Speedpanel3);
    lv_obj_set_width(ui_OnOffCarLabel18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel18, -61);
    lv_obj_set_y(ui_OnOffCarLabel18, 0);
    lv_obj_set_align(ui_OnOffCarLabel18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel18, "SPEED");
    lv_obj_set_style_text_font(ui_OnOffCarLabel18, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown5 = lv_dropdown_create(ui_Speedpanel3);
    lv_dropdown_set_options(ui_Dropdown5, "10%\n20%\n30%\n40%\n50%\n60%\n70%\n80%\n90%\n100%");
    lv_obj_set_width(ui_Dropdown5, 107);
    lv_obj_set_height(ui_Dropdown5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown5, 49);
    lv_obj_set_y(ui_Dropdown5, 0);
    lv_obj_set_align(ui_Dropdown5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_OnOffpanel16 = lv_obj_create(ui_Car3panel);
    lv_obj_set_width(ui_OnOffpanel16, 134);
    lv_obj_set_height(ui_OnOffpanel16, 54);
    lv_obj_set_x(ui_OnOffpanel16, 106);
    lv_obj_set_y(ui_OnOffpanel16, -66);
    lv_obj_set_align(ui_OnOffpanel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel19 = lv_label_create(ui_OnOffpanel16);
    lv_obj_set_width(ui_OnOffCarLabel19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel19, -36);
    lv_obj_set_y(ui_OnOffCarLabel19, 0);
    lv_obj_set_align(ui_OnOffCarLabel19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel19, "IO1");
    lv_obj_set_style_text_font(ui_OnOffCarLabel19, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn17 = lv_switch_create(ui_OnOffpanel16);
    lv_obj_set_width(ui_OnOffAllCarbtn17, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn17, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn17, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn17, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn17, LV_ALIGN_CENTER);

    ui_OnOffpanel17 = lv_obj_create(ui_Car3panel);
    lv_obj_set_width(ui_OnOffpanel17, 134);
    lv_obj_set_height(ui_OnOffpanel17, 54);
    lv_obj_set_x(ui_OnOffpanel17, 264);
    lv_obj_set_y(ui_OnOffpanel17, -65);
    lv_obj_set_align(ui_OnOffpanel17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel20 = lv_label_create(ui_OnOffpanel17);
    lv_obj_set_width(ui_OnOffCarLabel20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel20, -36);
    lv_obj_set_y(ui_OnOffCarLabel20, 0);
    lv_obj_set_align(ui_OnOffCarLabel20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel20, "IO2");
    lv_obj_set_style_text_font(ui_OnOffCarLabel20, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn18 = lv_switch_create(ui_OnOffpanel17);
    lv_obj_set_width(ui_OnOffAllCarbtn18, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn18, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn18, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn18, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn18, LV_ALIGN_CENTER);

    ui_OnOffpanel18 = lv_obj_create(ui_Car3panel);
    lv_obj_set_width(ui_OnOffpanel18, 134);
    lv_obj_set_height(ui_OnOffpanel18, 54);
    lv_obj_set_x(ui_OnOffpanel18, 106);
    lv_obj_set_y(ui_OnOffpanel18, -2);
    lv_obj_set_align(ui_OnOffpanel18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel21 = lv_label_create(ui_OnOffpanel18);
    lv_obj_set_width(ui_OnOffCarLabel21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel21, -36);
    lv_obj_set_y(ui_OnOffCarLabel21, 0);
    lv_obj_set_align(ui_OnOffCarLabel21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel21, "IO3");
    lv_obj_set_style_text_font(ui_OnOffCarLabel21, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn19 = lv_switch_create(ui_OnOffpanel18);
    lv_obj_set_width(ui_OnOffAllCarbtn19, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn19, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn19, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn19, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn19, LV_ALIGN_CENTER);

    ui_OnOffpanel19 = lv_obj_create(ui_Car3panel);
    lv_obj_set_width(ui_OnOffpanel19, 134);
    lv_obj_set_height(ui_OnOffpanel19, 54);
    lv_obj_set_x(ui_OnOffpanel19, 264);
    lv_obj_set_y(ui_OnOffpanel19, -2);
    lv_obj_set_align(ui_OnOffpanel19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel22 = lv_label_create(ui_OnOffpanel19);
    lv_obj_set_width(ui_OnOffCarLabel22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel22, -36);
    lv_obj_set_y(ui_OnOffCarLabel22, 0);
    lv_obj_set_align(ui_OnOffCarLabel22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel22, "IO4");
    lv_obj_set_style_text_font(ui_OnOffCarLabel22, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn20 = lv_switch_create(ui_OnOffpanel19);
    lv_obj_set_width(ui_OnOffAllCarbtn20, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn20, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn20, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn20, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn20, LV_ALIGN_CENTER);

    ui_OnOffpanel20 = lv_obj_create(ui_Car3panel);
    lv_obj_set_width(ui_OnOffpanel20, 134);
    lv_obj_set_height(ui_OnOffpanel20, 54);
    lv_obj_set_x(ui_OnOffpanel20, 264);
    lv_obj_set_y(ui_OnOffpanel20, 62);
    lv_obj_set_align(ui_OnOffpanel20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel23 = lv_label_create(ui_OnOffpanel20);
    lv_obj_set_width(ui_OnOffCarLabel23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel23, -36);
    lv_obj_set_y(ui_OnOffCarLabel23, 0);
    lv_obj_set_align(ui_OnOffCarLabel23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel23, "IO6");
    lv_obj_set_style_text_font(ui_OnOffCarLabel23, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn21 = lv_switch_create(ui_OnOffpanel20);
    lv_obj_set_width(ui_OnOffAllCarbtn21, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn21, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn21, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn21, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn21, LV_ALIGN_CENTER);

    ui_OnOffpanel21 = lv_obj_create(ui_Car3panel);
    lv_obj_set_width(ui_OnOffpanel21, 134);
    lv_obj_set_height(ui_OnOffpanel21, 54);
    lv_obj_set_x(ui_OnOffpanel21, 106);
    lv_obj_set_y(ui_OnOffpanel21, 63);
    lv_obj_set_align(ui_OnOffpanel21, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel24 = lv_label_create(ui_OnOffpanel21);
    lv_obj_set_width(ui_OnOffCarLabel24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel24, -36);
    lv_obj_set_y(ui_OnOffCarLabel24, 0);
    lv_obj_set_align(ui_OnOffCarLabel24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel24, "IO5");
    lv_obj_set_style_text_font(ui_OnOffCarLabel24, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn22 = lv_switch_create(ui_OnOffpanel21);
    lv_obj_set_width(ui_OnOffAllCarbtn22, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn22, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn22, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn22, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn22, LV_ALIGN_CENTER);

    ui_Batterypanel3 = lv_obj_create(ui_Car3panel);
    lv_obj_set_width(ui_Batterypanel3, 93);
    lv_obj_set_height(ui_Batterypanel3, 180);
    lv_obj_set_x(ui_Batterypanel3, -28);
    lv_obj_set_y(ui_Batterypanel3, 0);
    lv_obj_set_align(ui_Batterypanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Batterypanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Batterypanel3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 1);
    lv_obj_set_y(ui_Label6, -58);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "BAT");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Car3Batlabel = lv_label_create(ui_Batterypanel3);
    lv_obj_set_width(ui_Car3Batlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Car3Batlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Car3Batlabel, 0);
    lv_obj_set_y(ui_Car3Batlabel, 6);
    lv_obj_set_align(ui_Car3Batlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Car3Batlabel, "100%");
    lv_obj_set_style_text_color(ui_Car3Batlabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Car3Batlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Car3Batlabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Car3Batlabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Car4 = lv_tabview_add_tab(ui_CarStatus, "CAR 4");

    ui_Car4panel = lv_obj_create(ui_Car4);
    lv_obj_set_width(ui_Car4panel, 722);
    lv_obj_set_height(ui_Car4panel, 207);
    lv_obj_set_x(ui_Car4panel, -6);
    lv_obj_set_y(ui_Car4panel, 1);
    lv_obj_set_align(ui_Car4panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Car4panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Modepanel4 = lv_obj_create(ui_Car4panel);
    lv_obj_set_width(ui_Modepanel4, 228);
    lv_obj_set_height(ui_Modepanel4, 54);
    lv_obj_set_x(ui_Modepanel4, -214);
    lv_obj_set_y(ui_Modepanel4, 63);
    lv_obj_set_align(ui_Modepanel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Modepanel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ModeCarLabel4 = lv_label_create(ui_Modepanel4);
    lv_obj_set_width(ui_ModeCarLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ModeCarLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ModeCarLabel4, -61);
    lv_obj_set_y(ui_ModeCarLabel4, 0);
    lv_obj_set_align(ui_ModeCarLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ModeCarLabel4, "MODE");
    lv_obj_set_style_text_font(ui_ModeCarLabel4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorMode4 = lv_dropdown_create(ui_Modepanel4);
    lv_dropdown_set_options(ui_MotorMode4, "Mode 1\nMode 2\n");
    lv_obj_set_width(ui_MotorMode4, 107);
    lv_obj_set_height(ui_MotorMode4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorMode4, 49);
    lv_obj_set_y(ui_MotorMode4, 0);
    lv_obj_set_align(ui_MotorMode4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MotorMode4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_OnOffpanel22 = lv_obj_create(ui_Car4panel);
    lv_obj_set_width(ui_OnOffpanel22, 228);
    lv_obj_set_height(ui_OnOffpanel22, 54);
    lv_obj_set_x(ui_OnOffpanel22, -214);
    lv_obj_set_y(ui_OnOffpanel22, -66);
    lv_obj_set_align(ui_OnOffpanel22, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel25 = lv_label_create(ui_OnOffpanel22);
    lv_obj_set_width(ui_OnOffCarLabel25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel25, -56);
    lv_obj_set_y(ui_OnOffCarLabel25, 0);
    lv_obj_set_align(ui_OnOffCarLabel25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel25, "ON/OFF ");
    lv_obj_set_style_text_font(ui_OnOffCarLabel25, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn23 = lv_switch_create(ui_OnOffpanel22);
    lv_obj_set_width(ui_OnOffAllCarbtn23, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn23, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn23, 52);
    lv_obj_set_y(ui_OnOffAllCarbtn23, -1);
    lv_obj_set_align(ui_OnOffAllCarbtn23, LV_ALIGN_CENTER);

    ui_Speedpanel4 = lv_obj_create(ui_Car4panel);
    lv_obj_set_width(ui_Speedpanel4, 228);
    lv_obj_set_height(ui_Speedpanel4, 54);
    lv_obj_set_x(ui_Speedpanel4, -214);
    lv_obj_set_y(ui_Speedpanel4, -2);
    lv_obj_set_align(ui_Speedpanel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Speedpanel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel26 = lv_label_create(ui_Speedpanel4);
    lv_obj_set_width(ui_OnOffCarLabel26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel26, -61);
    lv_obj_set_y(ui_OnOffCarLabel26, 0);
    lv_obj_set_align(ui_OnOffCarLabel26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel26, "SPEED");
    lv_obj_set_style_text_font(ui_OnOffCarLabel26, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown6 = lv_dropdown_create(ui_Speedpanel4);
    lv_dropdown_set_options(ui_Dropdown6, "10%\n20%\n30%\n40%\n50%\n60%\n70%\n80%\n90%\n100%");
    lv_obj_set_width(ui_Dropdown6, 107);
    lv_obj_set_height(ui_Dropdown6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown6, 49);
    lv_obj_set_y(ui_Dropdown6, 0);
    lv_obj_set_align(ui_Dropdown6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_OnOffpanel23 = lv_obj_create(ui_Car4panel);
    lv_obj_set_width(ui_OnOffpanel23, 134);
    lv_obj_set_height(ui_OnOffpanel23, 54);
    lv_obj_set_x(ui_OnOffpanel23, 106);
    lv_obj_set_y(ui_OnOffpanel23, -66);
    lv_obj_set_align(ui_OnOffpanel23, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel27 = lv_label_create(ui_OnOffpanel23);
    lv_obj_set_width(ui_OnOffCarLabel27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel27, -36);
    lv_obj_set_y(ui_OnOffCarLabel27, 0);
    lv_obj_set_align(ui_OnOffCarLabel27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel27, "IO1");
    lv_obj_set_style_text_font(ui_OnOffCarLabel27, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn24 = lv_switch_create(ui_OnOffpanel23);
    lv_obj_set_width(ui_OnOffAllCarbtn24, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn24, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn24, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn24, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn24, LV_ALIGN_CENTER);

    ui_OnOffpanel24 = lv_obj_create(ui_Car4panel);
    lv_obj_set_width(ui_OnOffpanel24, 134);
    lv_obj_set_height(ui_OnOffpanel24, 54);
    lv_obj_set_x(ui_OnOffpanel24, 264);
    lv_obj_set_y(ui_OnOffpanel24, -65);
    lv_obj_set_align(ui_OnOffpanel24, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel28 = lv_label_create(ui_OnOffpanel24);
    lv_obj_set_width(ui_OnOffCarLabel28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel28, -36);
    lv_obj_set_y(ui_OnOffCarLabel28, 0);
    lv_obj_set_align(ui_OnOffCarLabel28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel28, "IO2");
    lv_obj_set_style_text_font(ui_OnOffCarLabel28, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn25 = lv_switch_create(ui_OnOffpanel24);
    lv_obj_set_width(ui_OnOffAllCarbtn25, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn25, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn25, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn25, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn25, LV_ALIGN_CENTER);

    ui_OnOffpanel25 = lv_obj_create(ui_Car4panel);
    lv_obj_set_width(ui_OnOffpanel25, 134);
    lv_obj_set_height(ui_OnOffpanel25, 54);
    lv_obj_set_x(ui_OnOffpanel25, 106);
    lv_obj_set_y(ui_OnOffpanel25, -2);
    lv_obj_set_align(ui_OnOffpanel25, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel29 = lv_label_create(ui_OnOffpanel25);
    lv_obj_set_width(ui_OnOffCarLabel29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel29, -36);
    lv_obj_set_y(ui_OnOffCarLabel29, 0);
    lv_obj_set_align(ui_OnOffCarLabel29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel29, "IO3");
    lv_obj_set_style_text_font(ui_OnOffCarLabel29, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn26 = lv_switch_create(ui_OnOffpanel25);
    lv_obj_set_width(ui_OnOffAllCarbtn26, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn26, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn26, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn26, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn26, LV_ALIGN_CENTER);

    ui_OnOffpanel26 = lv_obj_create(ui_Car4panel);
    lv_obj_set_width(ui_OnOffpanel26, 134);
    lv_obj_set_height(ui_OnOffpanel26, 54);
    lv_obj_set_x(ui_OnOffpanel26, 264);
    lv_obj_set_y(ui_OnOffpanel26, -2);
    lv_obj_set_align(ui_OnOffpanel26, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel30 = lv_label_create(ui_OnOffpanel26);
    lv_obj_set_width(ui_OnOffCarLabel30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel30, -36);
    lv_obj_set_y(ui_OnOffCarLabel30, 0);
    lv_obj_set_align(ui_OnOffCarLabel30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel30, "IO4");
    lv_obj_set_style_text_font(ui_OnOffCarLabel30, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn27 = lv_switch_create(ui_OnOffpanel26);
    lv_obj_set_width(ui_OnOffAllCarbtn27, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn27, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn27, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn27, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn27, LV_ALIGN_CENTER);

    ui_OnOffpanel27 = lv_obj_create(ui_Car4panel);
    lv_obj_set_width(ui_OnOffpanel27, 134);
    lv_obj_set_height(ui_OnOffpanel27, 54);
    lv_obj_set_x(ui_OnOffpanel27, 264);
    lv_obj_set_y(ui_OnOffpanel27, 62);
    lv_obj_set_align(ui_OnOffpanel27, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel31 = lv_label_create(ui_OnOffpanel27);
    lv_obj_set_width(ui_OnOffCarLabel31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel31, -36);
    lv_obj_set_y(ui_OnOffCarLabel31, 0);
    lv_obj_set_align(ui_OnOffCarLabel31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel31, "IO6");
    lv_obj_set_style_text_font(ui_OnOffCarLabel31, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn28 = lv_switch_create(ui_OnOffpanel27);
    lv_obj_set_width(ui_OnOffAllCarbtn28, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn28, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn28, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn28, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn28, LV_ALIGN_CENTER);

    ui_OnOffpanel28 = lv_obj_create(ui_Car4panel);
    lv_obj_set_width(ui_OnOffpanel28, 134);
    lv_obj_set_height(ui_OnOffpanel28, 54);
    lv_obj_set_x(ui_OnOffpanel28, 106);
    lv_obj_set_y(ui_OnOffpanel28, 63);
    lv_obj_set_align(ui_OnOffpanel28, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel32 = lv_label_create(ui_OnOffpanel28);
    lv_obj_set_width(ui_OnOffCarLabel32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel32, -36);
    lv_obj_set_y(ui_OnOffCarLabel32, 0);
    lv_obj_set_align(ui_OnOffCarLabel32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel32, "IO5");
    lv_obj_set_style_text_font(ui_OnOffCarLabel32, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn29 = lv_switch_create(ui_OnOffpanel28);
    lv_obj_set_width(ui_OnOffAllCarbtn29, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn29, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn29, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn29, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn29, LV_ALIGN_CENTER);

    ui_Batterypanel4 = lv_obj_create(ui_Car4panel);
    lv_obj_set_width(ui_Batterypanel4, 93);
    lv_obj_set_height(ui_Batterypanel4, 180);
    lv_obj_set_x(ui_Batterypanel4, -28);
    lv_obj_set_y(ui_Batterypanel4, 0);
    lv_obj_set_align(ui_Batterypanel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Batterypanel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Batterypanel4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 1);
    lv_obj_set_y(ui_Label8, -58);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "BAT");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Car4Batlabel = lv_label_create(ui_Batterypanel4);
    lv_obj_set_width(ui_Car4Batlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Car4Batlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Car4Batlabel, 0);
    lv_obj_set_y(ui_Car4Batlabel, 6);
    lv_obj_set_align(ui_Car4Batlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Car4Batlabel, "100%");
    lv_obj_set_style_text_color(ui_Car4Batlabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Car4Batlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Car4Batlabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Car4Batlabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Car5 = lv_tabview_add_tab(ui_CarStatus, "CAR 5");

    ui_Car5panel = lv_obj_create(ui_Car5);
    lv_obj_set_width(ui_Car5panel, 722);
    lv_obj_set_height(ui_Car5panel, 207);
    lv_obj_set_x(ui_Car5panel, -6);
    lv_obj_set_y(ui_Car5panel, 1);
    lv_obj_set_align(ui_Car5panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Car5panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Modepanel5 = lv_obj_create(ui_Car5panel);
    lv_obj_set_width(ui_Modepanel5, 228);
    lv_obj_set_height(ui_Modepanel5, 54);
    lv_obj_set_x(ui_Modepanel5, -214);
    lv_obj_set_y(ui_Modepanel5, 63);
    lv_obj_set_align(ui_Modepanel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Modepanel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ModeCarLabel5 = lv_label_create(ui_Modepanel5);
    lv_obj_set_width(ui_ModeCarLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ModeCarLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ModeCarLabel5, -61);
    lv_obj_set_y(ui_ModeCarLabel5, 0);
    lv_obj_set_align(ui_ModeCarLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ModeCarLabel5, "MODE");
    lv_obj_set_style_text_font(ui_ModeCarLabel5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorMode5 = lv_dropdown_create(ui_Modepanel5);
    lv_dropdown_set_options(ui_MotorMode5, "Mode 1\nMode 2\n");
    lv_obj_set_width(ui_MotorMode5, 107);
    lv_obj_set_height(ui_MotorMode5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorMode5, 49);
    lv_obj_set_y(ui_MotorMode5, 0);
    lv_obj_set_align(ui_MotorMode5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MotorMode5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_OnOffpanel29 = lv_obj_create(ui_Car5panel);
    lv_obj_set_width(ui_OnOffpanel29, 228);
    lv_obj_set_height(ui_OnOffpanel29, 54);
    lv_obj_set_x(ui_OnOffpanel29, -214);
    lv_obj_set_y(ui_OnOffpanel29, -66);
    lv_obj_set_align(ui_OnOffpanel29, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel33 = lv_label_create(ui_OnOffpanel29);
    lv_obj_set_width(ui_OnOffCarLabel33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel33, -56);
    lv_obj_set_y(ui_OnOffCarLabel33, 0);
    lv_obj_set_align(ui_OnOffCarLabel33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel33, "ON/OFF ");
    lv_obj_set_style_text_font(ui_OnOffCarLabel33, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn30 = lv_switch_create(ui_OnOffpanel29);
    lv_obj_set_width(ui_OnOffAllCarbtn30, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn30, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn30, 52);
    lv_obj_set_y(ui_OnOffAllCarbtn30, -1);
    lv_obj_set_align(ui_OnOffAllCarbtn30, LV_ALIGN_CENTER);

    ui_Speedpanel6 = lv_obj_create(ui_Car5panel);
    lv_obj_set_width(ui_Speedpanel6, 228);
    lv_obj_set_height(ui_Speedpanel6, 54);
    lv_obj_set_x(ui_Speedpanel6, -214);
    lv_obj_set_y(ui_Speedpanel6, -2);
    lv_obj_set_align(ui_Speedpanel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Speedpanel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel35 = lv_label_create(ui_Speedpanel6);
    lv_obj_set_width(ui_OnOffCarLabel35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel35, -61);
    lv_obj_set_y(ui_OnOffCarLabel35, 0);
    lv_obj_set_align(ui_OnOffCarLabel35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel35, "SPEED");
    lv_obj_set_style_text_font(ui_OnOffCarLabel35, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown7 = lv_dropdown_create(ui_Speedpanel6);
    lv_dropdown_set_options(ui_Dropdown7, "10%\n20%\n30%\n40%\n50%\n60%\n70%\n80%\n90%\n100%");
    lv_obj_set_width(ui_Dropdown7, 107);
    lv_obj_set_height(ui_Dropdown7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown7, 49);
    lv_obj_set_y(ui_Dropdown7, 0);
    lv_obj_set_align(ui_Dropdown7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_OnOffpanel30 = lv_obj_create(ui_Car5panel);
    lv_obj_set_width(ui_OnOffpanel30, 134);
    lv_obj_set_height(ui_OnOffpanel30, 54);
    lv_obj_set_x(ui_OnOffpanel30, 106);
    lv_obj_set_y(ui_OnOffpanel30, -66);
    lv_obj_set_align(ui_OnOffpanel30, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel36 = lv_label_create(ui_OnOffpanel30);
    lv_obj_set_width(ui_OnOffCarLabel36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel36, -36);
    lv_obj_set_y(ui_OnOffCarLabel36, 0);
    lv_obj_set_align(ui_OnOffCarLabel36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel36, "IO1");
    lv_obj_set_style_text_font(ui_OnOffCarLabel36, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn31 = lv_switch_create(ui_OnOffpanel30);
    lv_obj_set_width(ui_OnOffAllCarbtn31, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn31, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn31, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn31, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn31, LV_ALIGN_CENTER);

    ui_OnOffpanel31 = lv_obj_create(ui_Car5panel);
    lv_obj_set_width(ui_OnOffpanel31, 134);
    lv_obj_set_height(ui_OnOffpanel31, 54);
    lv_obj_set_x(ui_OnOffpanel31, 264);
    lv_obj_set_y(ui_OnOffpanel31, -65);
    lv_obj_set_align(ui_OnOffpanel31, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel37 = lv_label_create(ui_OnOffpanel31);
    lv_obj_set_width(ui_OnOffCarLabel37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel37, -36);
    lv_obj_set_y(ui_OnOffCarLabel37, 0);
    lv_obj_set_align(ui_OnOffCarLabel37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel37, "IO2");
    lv_obj_set_style_text_font(ui_OnOffCarLabel37, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn32 = lv_switch_create(ui_OnOffpanel31);
    lv_obj_set_width(ui_OnOffAllCarbtn32, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn32, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn32, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn32, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn32, LV_ALIGN_CENTER);

    ui_OnOffpanel32 = lv_obj_create(ui_Car5panel);
    lv_obj_set_width(ui_OnOffpanel32, 134);
    lv_obj_set_height(ui_OnOffpanel32, 54);
    lv_obj_set_x(ui_OnOffpanel32, 106);
    lv_obj_set_y(ui_OnOffpanel32, -2);
    lv_obj_set_align(ui_OnOffpanel32, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel38 = lv_label_create(ui_OnOffpanel32);
    lv_obj_set_width(ui_OnOffCarLabel38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel38, -36);
    lv_obj_set_y(ui_OnOffCarLabel38, 0);
    lv_obj_set_align(ui_OnOffCarLabel38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel38, "IO3");
    lv_obj_set_style_text_font(ui_OnOffCarLabel38, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn33 = lv_switch_create(ui_OnOffpanel32);
    lv_obj_set_width(ui_OnOffAllCarbtn33, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn33, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn33, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn33, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn33, LV_ALIGN_CENTER);

    ui_OnOffpanel33 = lv_obj_create(ui_Car5panel);
    lv_obj_set_width(ui_OnOffpanel33, 134);
    lv_obj_set_height(ui_OnOffpanel33, 54);
    lv_obj_set_x(ui_OnOffpanel33, 264);
    lv_obj_set_y(ui_OnOffpanel33, -2);
    lv_obj_set_align(ui_OnOffpanel33, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel39 = lv_label_create(ui_OnOffpanel33);
    lv_obj_set_width(ui_OnOffCarLabel39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel39, -36);
    lv_obj_set_y(ui_OnOffCarLabel39, 0);
    lv_obj_set_align(ui_OnOffCarLabel39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel39, "IO4");
    lv_obj_set_style_text_font(ui_OnOffCarLabel39, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn34 = lv_switch_create(ui_OnOffpanel33);
    lv_obj_set_width(ui_OnOffAllCarbtn34, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn34, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn34, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn34, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn34, LV_ALIGN_CENTER);

    ui_OnOffpanel34 = lv_obj_create(ui_Car5panel);
    lv_obj_set_width(ui_OnOffpanel34, 134);
    lv_obj_set_height(ui_OnOffpanel34, 54);
    lv_obj_set_x(ui_OnOffpanel34, 264);
    lv_obj_set_y(ui_OnOffpanel34, 62);
    lv_obj_set_align(ui_OnOffpanel34, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel40 = lv_label_create(ui_OnOffpanel34);
    lv_obj_set_width(ui_OnOffCarLabel40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel40, -36);
    lv_obj_set_y(ui_OnOffCarLabel40, 0);
    lv_obj_set_align(ui_OnOffCarLabel40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel40, "IO6");
    lv_obj_set_style_text_font(ui_OnOffCarLabel40, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn35 = lv_switch_create(ui_OnOffpanel34);
    lv_obj_set_width(ui_OnOffAllCarbtn35, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn35, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn35, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn35, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn35, LV_ALIGN_CENTER);

    ui_OnOffpanel35 = lv_obj_create(ui_Car5panel);
    lv_obj_set_width(ui_OnOffpanel35, 134);
    lv_obj_set_height(ui_OnOffpanel35, 54);
    lv_obj_set_x(ui_OnOffpanel35, 106);
    lv_obj_set_y(ui_OnOffpanel35, 63);
    lv_obj_set_align(ui_OnOffpanel35, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OnOffpanel35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnOffCarLabel41 = lv_label_create(ui_OnOffpanel35);
    lv_obj_set_width(ui_OnOffCarLabel41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffCarLabel41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffCarLabel41, -36);
    lv_obj_set_y(ui_OnOffCarLabel41, 0);
    lv_obj_set_align(ui_OnOffCarLabel41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffCarLabel41, "IO5");
    lv_obj_set_style_text_font(ui_OnOffCarLabel41, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffAllCarbtn36 = lv_switch_create(ui_OnOffpanel35);
    lv_obj_set_width(ui_OnOffAllCarbtn36, 58);
    lv_obj_set_height(ui_OnOffAllCarbtn36, 28);
    lv_obj_set_x(ui_OnOffAllCarbtn36, 22);
    lv_obj_set_y(ui_OnOffAllCarbtn36, 0);
    lv_obj_set_align(ui_OnOffAllCarbtn36, LV_ALIGN_CENTER);

    ui_Batterypanel5 = lv_obj_create(ui_Car5panel);
    lv_obj_set_width(ui_Batterypanel5, 93);
    lv_obj_set_height(ui_Batterypanel5, 180);
    lv_obj_set_x(ui_Batterypanel5, -28);
    lv_obj_set_y(ui_Batterypanel5, 0);
    lv_obj_set_align(ui_Batterypanel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Batterypanel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Batterypanel5);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 1);
    lv_obj_set_y(ui_Label10, -58);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "BAT");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Car5Batlabel = lv_label_create(ui_Batterypanel5);
    lv_obj_set_width(ui_Car5Batlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Car5Batlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Car5Batlabel, 0);
    lv_obj_set_y(ui_Car5Batlabel, 6);
    lv_obj_set_align(ui_Car5Batlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Car5Batlabel, "100%");
    lv_obj_set_style_text_color(ui_Car5Batlabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Car5Batlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Car5Batlabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Car5Batlabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusArea = lv_textarea_create(ui_MainPanel);
    lv_obj_set_width(ui_StatusArea, 436);
    lv_obj_set_height(ui_StatusArea, 138);
    lv_obj_set_x(ui_StatusArea, 130);
    lv_obj_set_y(ui_StatusArea, -143);
    lv_obj_set_align(ui_StatusArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_StatusArea, "Status...");

    ui_SpeedAllpanel = lv_obj_create(ui_MainPanel);
    lv_obj_set_width(ui_SpeedAllpanel, 254);
    lv_obj_set_height(ui_SpeedAllpanel, 66);
    lv_obj_set_x(ui_SpeedAllpanel, -233);
    lv_obj_set_y(ui_SpeedAllpanel, -105);
    lv_obj_set_align(ui_SpeedAllpanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpeedAllpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SpeedAllCarLabel = lv_label_create(ui_SpeedAllpanel);
    lv_obj_set_width(ui_SpeedAllCarLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedAllCarLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedAllCarLabel, -70);
    lv_obj_set_y(ui_SpeedAllCarLabel, -2);
    lv_obj_set_align(ui_SpeedAllCarLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedAllCarLabel, "SPEED");
    lv_obj_set_style_text_font(ui_SpeedAllCarLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedAllCardropdown = lv_dropdown_create(ui_SpeedAllpanel);
    lv_dropdown_set_options(ui_SpeedAllCardropdown, "10%\n20%\n30%\n40%\n50%\n60%\n70%\n80%\n90%\n100%");
    lv_obj_set_width(ui_SpeedAllCardropdown, 107);
    lv_obj_set_height(ui_SpeedAllCardropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedAllCardropdown, 57);
    lv_obj_set_y(ui_SpeedAllCardropdown, 0);
    lv_obj_set_align(ui_SpeedAllCardropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SpeedAllCardropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_OnOffAllCarbtn = lv_switch_create(ui_MainPanel);
    lv_obj_set_width(ui_OnOffAllCarbtn, 235);
    lv_obj_set_height(ui_OnOffAllCarbtn, 73);
    lv_obj_set_x(ui_OnOffAllCarbtn, -234);
    lv_obj_set_y(ui_OnOffAllCarbtn, -182);
    lv_obj_set_align(ui_OnOffAllCarbtn, LV_ALIGN_CENTER);

    ui_OnOffAllCarlabel = lv_label_create(ui_MainPanel);
    lv_obj_set_width(ui_OnOffAllCarlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffAllCarlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffAllCarlabel, -234);
    lv_obj_set_y(ui_OnOffAllCarlabel, -181);
    lv_obj_set_align(ui_OnOffAllCarlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffAllCarlabel, "ON/OFF\nALL CAR");
    lv_obj_set_style_text_font(ui_OnOffAllCarlabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MotorMode, ui_event_MotorMode, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn3, ui_event_OnOffAllCarbtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown2, ui_event_Dropdown2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn2, ui_event_OnOffAllCarbtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn4, ui_event_OnOffAllCarbtn4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn1, ui_event_OnOffAllCarbtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn5, ui_event_OnOffAllCarbtn5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn6, ui_event_OnOffAllCarbtn6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn7, ui_event_OnOffAllCarbtn7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MotorMode2, ui_event_MotorMode2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn15, ui_event_OnOffAllCarbtn15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown4, ui_event_Dropdown4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn8, ui_event_OnOffAllCarbtn8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn9, ui_event_OnOffAllCarbtn9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn10, ui_event_OnOffAllCarbtn10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn11, ui_event_OnOffAllCarbtn11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn12, ui_event_OnOffAllCarbtn12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn13, ui_event_OnOffAllCarbtn13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MotorMode3, ui_event_MotorMode3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn16, ui_event_OnOffAllCarbtn16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown5, ui_event_Dropdown5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn17, ui_event_OnOffAllCarbtn17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn18, ui_event_OnOffAllCarbtn18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn19, ui_event_OnOffAllCarbtn19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn20, ui_event_OnOffAllCarbtn20, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn21, ui_event_OnOffAllCarbtn21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn22, ui_event_OnOffAllCarbtn22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MotorMode4, ui_event_MotorMode4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn23, ui_event_OnOffAllCarbtn23, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown6, ui_event_Dropdown6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn24, ui_event_OnOffAllCarbtn24, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn25, ui_event_OnOffAllCarbtn25, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn26, ui_event_OnOffAllCarbtn26, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn27, ui_event_OnOffAllCarbtn27, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn28, ui_event_OnOffAllCarbtn28, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn29, ui_event_OnOffAllCarbtn29, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MotorMode5, ui_event_MotorMode5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn30, ui_event_OnOffAllCarbtn30, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown7, ui_event_Dropdown7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn31, ui_event_OnOffAllCarbtn31, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn32, ui_event_OnOffAllCarbtn32, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn33, ui_event_OnOffAllCarbtn33, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn34, ui_event_OnOffAllCarbtn34, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn35, ui_event_OnOffAllCarbtn35, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn36, ui_event_OnOffAllCarbtn36, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SpeedAllCardropdown, ui_event_SpeedAllCardropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOffAllCarbtn, ui_event_OnOffAllCarbtn, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_MainPanel = NULL;
    ui_CarStatus = NULL;
    ui_Car1 = NULL;
    ui_Car1panel = NULL;
    ui_Modepanel = NULL;
    ui_ModeCarLabel = NULL;
    ui_MotorMode = NULL;
    ui_OnOffpanel = NULL;
    ui_OnOffCarLabel = NULL;
    ui_OnOffAllCarbtn3 = NULL;
    ui_Speedpanel = NULL;
    ui_OnOffCarLabel3 = NULL;
    ui_Dropdown2 = NULL;
    ui_OnOffpanel2 = NULL;
    ui_OnOffCarLabel2 = NULL;
    ui_OnOffAllCarbtn2 = NULL;
    ui_OnOffpanel3 = NULL;
    ui_OnOffCarLabel4 = NULL;
    ui_OnOffAllCarbtn4 = NULL;
    ui_OnOffpanel1 = NULL;
    ui_OnOffCarLabel1 = NULL;
    ui_OnOffAllCarbtn1 = NULL;
    ui_OnOffpanel4 = NULL;
    ui_OnOffCarLabel5 = NULL;
    ui_OnOffAllCarbtn5 = NULL;
    ui_OnOffpanel5 = NULL;
    ui_OnOffCarLabel6 = NULL;
    ui_OnOffAllCarbtn6 = NULL;
    ui_OnOffpanel6 = NULL;
    ui_OnOffCarLabel7 = NULL;
    ui_OnOffAllCarbtn7 = NULL;
    ui_Batterypanel = NULL;
    ui_Label2 = NULL;
    ui_Car1Batlabel = NULL;
    ui_Car2 = NULL;
    ui_Car2panel = NULL;
    ui_Modepanel2 = NULL;
    ui_ModeCarLabel2 = NULL;
    ui_MotorMode2 = NULL;
    ui_OnOffpanel14 = NULL;
    ui_OnOffCarLabel16 = NULL;
    ui_OnOffAllCarbtn15 = NULL;
    ui_Speedpanel2 = NULL;
    ui_OnOffCarLabel8 = NULL;
    ui_Dropdown4 = NULL;
    ui_OnOffpanel7 = NULL;
    ui_OnOffCarLabel9 = NULL;
    ui_OnOffAllCarbtn8 = NULL;
    ui_OnOffpanel8 = NULL;
    ui_OnOffCarLabel10 = NULL;
    ui_OnOffAllCarbtn9 = NULL;
    ui_OnOffpanel9 = NULL;
    ui_OnOffCarLabel11 = NULL;
    ui_OnOffAllCarbtn10 = NULL;
    ui_OnOffpanel10 = NULL;
    ui_OnOffCarLabel12 = NULL;
    ui_OnOffAllCarbtn11 = NULL;
    ui_OnOffpanel11 = NULL;
    ui_OnOffCarLabel13 = NULL;
    ui_OnOffAllCarbtn12 = NULL;
    ui_OnOffpanel12 = NULL;
    ui_OnOffCarLabel14 = NULL;
    ui_OnOffAllCarbtn13 = NULL;
    ui_Batterypanel2 = NULL;
    ui_Label5 = NULL;
    ui_Car2Batlabel = NULL;
    ui_Car3 = NULL;
    ui_Car3panel = NULL;
    ui_Modepanel3 = NULL;
    ui_ModeCarLabel3 = NULL;
    ui_MotorMode3 = NULL;
    ui_OnOffpanel15 = NULL;
    ui_OnOffCarLabel17 = NULL;
    ui_OnOffAllCarbtn16 = NULL;
    ui_Speedpanel3 = NULL;
    ui_OnOffCarLabel18 = NULL;
    ui_Dropdown5 = NULL;
    ui_OnOffpanel16 = NULL;
    ui_OnOffCarLabel19 = NULL;
    ui_OnOffAllCarbtn17 = NULL;
    ui_OnOffpanel17 = NULL;
    ui_OnOffCarLabel20 = NULL;
    ui_OnOffAllCarbtn18 = NULL;
    ui_OnOffpanel18 = NULL;
    ui_OnOffCarLabel21 = NULL;
    ui_OnOffAllCarbtn19 = NULL;
    ui_OnOffpanel19 = NULL;
    ui_OnOffCarLabel22 = NULL;
    ui_OnOffAllCarbtn20 = NULL;
    ui_OnOffpanel20 = NULL;
    ui_OnOffCarLabel23 = NULL;
    ui_OnOffAllCarbtn21 = NULL;
    ui_OnOffpanel21 = NULL;
    ui_OnOffCarLabel24 = NULL;
    ui_OnOffAllCarbtn22 = NULL;
    ui_Batterypanel3 = NULL;
    ui_Label6 = NULL;
    ui_Car3Batlabel = NULL;
    ui_Car4 = NULL;
    ui_Car4panel = NULL;
    ui_Modepanel4 = NULL;
    ui_ModeCarLabel4 = NULL;
    ui_MotorMode4 = NULL;
    ui_OnOffpanel22 = NULL;
    ui_OnOffCarLabel25 = NULL;
    ui_OnOffAllCarbtn23 = NULL;
    ui_Speedpanel4 = NULL;
    ui_OnOffCarLabel26 = NULL;
    ui_Dropdown6 = NULL;
    ui_OnOffpanel23 = NULL;
    ui_OnOffCarLabel27 = NULL;
    ui_OnOffAllCarbtn24 = NULL;
    ui_OnOffpanel24 = NULL;
    ui_OnOffCarLabel28 = NULL;
    ui_OnOffAllCarbtn25 = NULL;
    ui_OnOffpanel25 = NULL;
    ui_OnOffCarLabel29 = NULL;
    ui_OnOffAllCarbtn26 = NULL;
    ui_OnOffpanel26 = NULL;
    ui_OnOffCarLabel30 = NULL;
    ui_OnOffAllCarbtn27 = NULL;
    ui_OnOffpanel27 = NULL;
    ui_OnOffCarLabel31 = NULL;
    ui_OnOffAllCarbtn28 = NULL;
    ui_OnOffpanel28 = NULL;
    ui_OnOffCarLabel32 = NULL;
    ui_OnOffAllCarbtn29 = NULL;
    ui_Batterypanel4 = NULL;
    ui_Label8 = NULL;
    ui_Car4Batlabel = NULL;
    ui_Car5 = NULL;
    ui_Car5panel = NULL;
    ui_Modepanel5 = NULL;
    ui_ModeCarLabel5 = NULL;
    ui_MotorMode5 = NULL;
    ui_OnOffpanel29 = NULL;
    ui_OnOffCarLabel33 = NULL;
    ui_OnOffAllCarbtn30 = NULL;
    ui_Speedpanel6 = NULL;
    ui_OnOffCarLabel35 = NULL;
    ui_Dropdown7 = NULL;
    ui_OnOffpanel30 = NULL;
    ui_OnOffCarLabel36 = NULL;
    ui_OnOffAllCarbtn31 = NULL;
    ui_OnOffpanel31 = NULL;
    ui_OnOffCarLabel37 = NULL;
    ui_OnOffAllCarbtn32 = NULL;
    ui_OnOffpanel32 = NULL;
    ui_OnOffCarLabel38 = NULL;
    ui_OnOffAllCarbtn33 = NULL;
    ui_OnOffpanel33 = NULL;
    ui_OnOffCarLabel39 = NULL;
    ui_OnOffAllCarbtn34 = NULL;
    ui_OnOffpanel34 = NULL;
    ui_OnOffCarLabel40 = NULL;
    ui_OnOffAllCarbtn35 = NULL;
    ui_OnOffpanel35 = NULL;
    ui_OnOffCarLabel41 = NULL;
    ui_OnOffAllCarbtn36 = NULL;
    ui_Batterypanel5 = NULL;
    ui_Label10 = NULL;
    ui_Car5Batlabel = NULL;
    ui_StatusArea = NULL;
    ui_SpeedAllpanel = NULL;
    ui_SpeedAllCarLabel = NULL;
    ui_SpeedAllCardropdown = NULL;
    ui_OnOffAllCarbtn = NULL;
    ui_OnOffAllCarlabel = NULL;

}
