// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Car_gui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Car1Mode(lv_event_t * e);
void Car1OnOff(lv_event_t * e);
void Car1Speed(lv_event_t * e);
void Car1Io1Func(lv_event_t * e);
void Car1Io2Func(lv_event_t * e);
void Car1Io3Func(lv_event_t * e);
void Car1Io4Func(lv_event_t * e);
void Car1Io6Func(lv_event_t * e);
void Car1Io5Func(lv_event_t * e);
void Car2Mode(lv_event_t * e);
void Car2OnOff(lv_event_t * e);
void Car2Speed(lv_event_t * e);
void Car2Io1Func(lv_event_t * e);
void Car2Io2Func(lv_event_t * e);
void Car2Io3Func(lv_event_t * e);
void Car2Io4Func(lv_event_t * e);
void Car2Io6Func(lv_event_t * e);
void Car2Io5Func(lv_event_t * e);
void Car3Mode(lv_event_t * e);
void Car3OnOff(lv_event_t * e);
void Car3Speed(lv_event_t * e);
void Car3Io1Func(lv_event_t * e);
void Car3Io2Func(lv_event_t * e);
void Car3Io3Func(lv_event_t * e);
void Car3Io4Func(lv_event_t * e);
void Car3Io6Func(lv_event_t * e);
void Car3Io5Func(lv_event_t * e);
void Car4Mode(lv_event_t * e);
void Car4OnOff(lv_event_t * e);
void Car4Speed(lv_event_t * e);
void Car4Io1Func(lv_event_t * e);
void Car4Io2Func(lv_event_t * e);
void Car4Io3Func(lv_event_t * e);
void Car4Io4Func(lv_event_t * e);
void Car4Io6Func(lv_event_t * e);
void Car4Io5Func(lv_event_t * e);
void Car5Mode(lv_event_t * e);
void Car5OnOff(lv_event_t * e);
void Car5Speed(lv_event_t * e);
void Car5Io1Func(lv_event_t * e);
void Car5Io2Func(lv_event_t * e);
void Car5Io3Func(lv_event_t * e);
void Car5Io4Func(lv_event_t * e);
void Car5Io6Func(lv_event_t * e);
void Car5Io5Func(lv_event_t * e);
void OnOffAllCar(lv_event_t * e);
void SpeedAll(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
