// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Car_gui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Car1Mode(lv_event_t * e);
void Car1OnOff(lv_event_t * e);
void Car1Io1Func(lv_event_t * e);
void Car1Io2Func(lv_event_t * e);
void Car1Io3Func(lv_event_t * e);
void Car1Io4Func(lv_event_t * e);
void Car1Io6Func(lv_event_t * e);
void Car1Io5Func(lv_event_t * e);
void OnOffAllCar(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
